# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The life and times of Dr John Dee
author:
  key: "Cole, Jordan"
  email: feedback@drjohndee.net
description: >- # this means to ignore newlines until "baseurl:"
  Dr Dee’s life and writings, presented with context, from source materials.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.drjohndee.net" # the base hostname & protocol for your site, e.g. http://example.com

lang: en-US

# site metadata
default_calendar_system: "Julian"
doi: "10.5281/zenodo.4511512"
github_repository_url: "https://github.com/stilist/drjohndee.net"
google_site_verification_key: "uYkaZuprDK3QILI95IPoJrtWcy0RJIgPGVMrLGIvsQM"
icon_name: heiroglyph
icon_sizes:
  - 16
  - 32
  - 64
  - 96
  - 128
  - 192
license_key: "CC BY-SA 4.0"
mapbox_access_token: "pk.eyJ1Ijoic3RpbGlzdCIsImEiOiJ2cXFLaVcwIn0.IrZVlgan0nuWCSTGlzbteg"
subject_person_key: "Dee, John"
theme_color:
  # --accent-60 (dark theme)
  dark: "#ae7022"
  # --accent-60--components (dark theme)
  dark_wide_gamut: "0.68 0.44 0.13"
  # --accent-60 (light theme)
  light: "#994900"
  # --accent-60--components (light theme)
  light_wide_gamut: "0.6 0.29 0"
twitter:
  username: stilist

# Build settings
cache_dir: &cache_dir _cache.nosync # `.nosync` prevents iCloud from syncing files
destination: _site.nosync
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - *cache_dir
  - .gitignore
  - .github/
  - .ruby-version
  - .terraform.lock.hcl
  - .terraform/
  - CHANGELOG.md
  - CITATION.cff
  - Code of conduct.md
  - CONTRIBUTING.md
  - Developer certificate of origin.txt
  - LICENSE.md
  - README.md
  - terraform/
  - untracked/

collections:
  source_documents:

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "date"
