"Autobiographical Tracts of Dr. John Dee":
  title: Autobiographical Tracts of Dr. John Dee, Warden of the College of Manchester
  author: Dee, John
  date: 1851
  license: public domain
  url: https://archive.org/details/autobiographical00deej/
  oclc_number: 1039961450
"British Society for the History of Mathematics":
  title: The British Society for the History of Mathematics
  author: Singmaster, David
  language: en
  url: https://web.archive.org/web/20120514145358/http://www.dcs.warwick.ac.uk/bshm/gazetteer.html
"Brytanici Imperii Limites":
  title: Brytanici Imperij Limites
  author: Dee, John
  license: public domain
"De gestis Britonum":
  title: De gestis Britonum
  author: Geoffrey of Monmouth
  date: 1136
  language: la-medieval
  license: public domain
  id: https://www.wikidata.org/entity/Q238693
  oclc_number: 1135980775
"Dictionary of National Biography, 1885–1900":
  title: Dictionary of National Biography, 1885–1900
  date: 1900
  language: en
  license: public domain
  id: https://www.wikidata.org/entity/Q15987216
  url: https://en.wikisource.org/wiki/Dictionary_of_National_Biography,_1885-1900/Vol_40_Myllar_-_Nicholls
  oclc_number: 1070788669
  volume_number: 40
"Environs of London, Surrey":
  title: The Environs of London
  author: Lysons, Daniel
  date: 1792
  volume_number: 1, County of Surrey
"Hexameron Brytanicum":
  title: The General and Rare Memorials pertayning to the Perfect Arte of Navigation
  author: Dee, John
  date: 1577
  language: en-emodeng
  license: public domain
  url: https://www.bl.uk/collection-items/john-dees-general-and-rare-memorials-bound-with-a-signed-manuscript
  oclc_number: 216607672
"Imperium Brytanicum":
  title: Imperium Brytanicum
  author: Dee, John
  license: public domain
  date: 1577/1578
"John Elmeston essay":
  title: >-
    An essay for the discovery and discouraging of the new sprung schism raised
    and maintained by Mr Simon Henden of Bennenden in Kent. Exhibited in some
    passages of writing which have gone between Mr John Elmeston of Cranebroke,
    and the same M. Henden. Published according to order.
  author: Elmeston, John
  language: en-emodeng
  license: public domain
  id: http://purl.ox.ac.uk/ota/A43313
  url: https://ota.bodleian.ox.ac.uk/repository/xmlui/handle/20.500.12024/A43313?show=full
  date: 1652
"Monas Hieroglyphica":
  title: Monas Hieroglyphica
  author: Dee, John
  date: 1564
  license: public domain
  id: https://www.wikidata.org/entity/Q908061
  url: https://archive.org/details/monashieroglyphi00deej
  oclc_number: 705418432
"New England Historical and Genealogical Register":
  title: The New England Historical and Genealogical Register
  date: 1913
  language: en
  license: public domain
  id: http://www.worldcat.org/oclc/2564052
  url: https://books.google.com/books?id=IsMMAAAAYAAJ
  oclc_number: 2564052
  volume_number: ⅬⅩⅤⅠⅠ
"Tables and Indexes, vol. 41":
  title: Tables and Indexes
  date: 1845
  language: en
  license: public domain
  url: https://www.google.com/books/edition/Tables_and_Indexes/IxVcAAAAQAAJ
  volume_number: 41
"The Private Diary of Dr. John Dee":
  title: The Private Diary of Dr. John Dee
  author: Dee, John
  date: 1842
  editor: Council of the Camden Society
  language: en-emodeng
  license: public domain
  url: https://archive.org/details/privatediaryofdr00deejuoft
  id: http://www.worldcat.org/oclc/1050791672
  oclc_number: 1050791672
