"Dictionary of National Biography, 1885–1900":
  title: Dictionary of National Biography, 1885–1900
  author: Radford, Emma Louisa
  date: 1900
  license: public domain
  id: https://www.wikidata.org/entity/Q15987216
  url: https://en.wikisource.org/wiki/Dictionary_of_National_Biography,_1885-1900/Vol_40_Myllar_-_Nicholls
  oclc_number: 1070788669
  volume_number: 40
"Hexameron Brytanicum":
  title: The General and Rare Memorials pertayning to the Perfect Arte of Navigation
  author: Dee, John
  date: 1577
  language: en-emodeng
  license: public domain
  url: https://www.bl.uk/collection-items/john-dees-general-and-rare-memorials-bound-with-a-signed-manuscript
  oclc_number: 216607672
"Monas Hieroglyphica":
  title: Monas Hieroglyphica
  author: Dee, John
  date: 1564
  license: public domain
  id: https://www.wikidata.org/entity/Q908061
  url: https://archive.org/details/monashieroglyphi00deej
  oclc_number: 705418432
"New England Historical and Genealogical Register":
  title: The New England Historical and Genealogical Register
  date: 1913
  license: public domain
  id: http://www.worldcat.org/oclc/2564052
  url: https://books.google.com/books?id=IsMMAAAAYAAJ
  oclc_number: 2564052
  volume_number: ⅬⅩⅤⅠⅠ
"Tables and Indexes, vol. 41":
  title: Tables and Indexes
  date: 1845
  license: public domain
  url: https://www.google.com/books/edition/Tables_and_Indexes/IxVcAAAAQAAJ
  volume_number: 41
"The Private Diary of Dr. John Dee":
  title: The Private Diary of Dr. John Dee
  author: Dee, John
  date: 1842
  editor: Council of the Camden Society
  language: en-emodeng
  license: public domain
  url: https://archive.org/details/privatediaryofdr00deejuoft
  id: http://www.worldcat.org/oclc/1050791672
  oclc_number: 1050791672
