"The Private Diary of Dr. John Dee":
  title: The Private Diary of Dr. John Dee
  author: Dee, John
  date: 1842
  editor: Council of the Camden Society
  url: https://archive.org/details/privatediaryofdr00deejuoft
  id: http://www.worldcat.org/oclc/1050791672
  oclc_number: 1050791672
